POST http://localhost:3003/api/blogs
Authorization: bearer <token>
Content-Type: application/json

{
    "title": "Loopy",
    "author": "Uncle Bob",
    "url": "https://blog.cleancoder.com/uncle-bob/2020/09/30/loopy.html"
}