POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Gordon Freeman",
    "number": "28932343247"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "A",
    "number": "28932343247"
}